site_name: Analizador ag09
pages:
    - Descripción: index.md
    - Descarga e instalación: descarga.md
    - Uso: uso.md
    - Lista de opciones: listaopc.md
    - Contacto: contacto.md

theme: sphinx_rtd_theme
