theme: jekyll-theme-hacker

download:
  source:           "https://github.com/twbs/bootstrap/archive/v4.1.1.zip"
  dist:             "https://github.com/twbs/bootstrap/releases/download/v4.1.1/bootstrap-4.1.1-dist.zip"
